
      #:schema node_modules/wrangler/config-schema.json
      name = "rin-server"
      main = "server/src/_worker.ts"
      compatibility_date = "2026-01-20"

      [assets]
      directory = "./dist/client"
      binding = "ASSETS"
      
[triggers]
crons = ["*/20 * * * *"]
      
      

      [vars]
      S3_FOLDER = "images/"
      S3_CACHE_FOLDER="cache/"
      S3_REGION = "auto"
      S3_ENDPOINT = "https://example.r2.cloudflarestorage.com"
      S3_ACCESS_HOST = "https://example.com"
      S3_BUCKET = "my-bucket"
      S3_FORCE_PATH_STYLE = "false"
      WEBHOOK_URL = ""
      RSS_TITLE = "Rin Development"
      RSS_DESCRIPTION = "Development Environment"
      CACHE_STORAGE_MODE = "database"
      NAME = "Rin"
      DESCRIPTION = "My Personal Blog"
      AVATAR = "https://s2.loli.net/2024/09/12/M5JyBnsioaWSgPA.jpg"
      PAGE_SIZE = "5"
      RSS_ENABLE = "false"

      [placement]
      mode = "smart"
    
[[d1_databases]]
binding = "DB"
database_name = "rin"
database_id = "8178e79e-5d95-4b8f-8d6c-0b2365319255"
    

[ai]
binding = "AI"
  

[[queues.producers]]
binding = "TASK_QUEUE"
queue = "rin-server-tasks"

[[queues.consumers]]
queue = "rin-server-tasks"
max_batch_size = 1
max_batch_timeout = 5
  
