name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install --registry https://registry.npmmirror.com
      - run: bun run deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NAME: ${{ vars.NAME }}
          DESCRIPTION: ${{ vars.DESCRIPTION }}
          AVATAR: ${{ vars.AVATAR }}
          PAGE_SIZE: ${{ vars.PAGE_SIZE }}
          RSS_ENABLE: ${{ vars.RSS_ENABLE }}
          R2_BUCKET_NAME: ${{ vars.R2_BUCKET_NAME }}
